package SCs_for_Energy_Trading;

/*Generated by MPS */

import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.ClassRule;
import jetbrains.mps.lang.test.runtime.TestParametersCache;
import org.junit.Rule;
import jetbrains.mps.lang.test.runtime.RunWithCommand;
import org.junit.Test;
import jetbrains.mps.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTestBody;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.iets3.core.expr.tests.rt.runtime.TestRunner;
import jetbrains.mps.lang.test.runtime.TransformationTest;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TestTrading_Test extends BaseTransformationTest {

  @ClassRule
  public static final TestParametersCache ourParamCache = new TestParametersCache(TestTrading_Test.class, "", "r:14b63796-e2a7-4c37-880c-9c969e9d77d7(SCs_for_Energy_Trading)", false);

  @Rule
  public final RunWithCommand myWithCommandRule = new RunWithCommand(this);

  public TestTrading_Test() {
    super(ourParamCache);
  }


  @Test
  public void TestTrading_item0_6249807012730451203() throws Throwable {
    new TestBody(this).TestTrading_item0_6249807012730451203();
  }
  @Test
  public void TestTrading_item1_6249807012730471594() throws Throwable {
    new TestBody(this).TestTrading_item1_6249807012730471594();
  }
  @Test
  public void TestTrading_item2_6249807012730889478() throws Throwable {
    new TestBody(this).TestTrading_item2_6249807012730889478();
  }


  @MPSLaunch
  public static class TestBody extends BaseTestBody {

    public void TestTrading_item0_6249807012730451203() throws Exception {
      SNode ti = SNodeOperations.cast(getRealNodeById("6249807012730451203"), CONCEPTS.AbstractTestItem$9u);
      TestRunner.doExecuteTest(ti);
    }
    public void TestTrading_item1_6249807012730471594() throws Exception {
      SNode ti = SNodeOperations.cast(getRealNodeById("6249807012730471594"), CONCEPTS.AbstractTestItem$9u);
      TestRunner.doExecuteTest(ti);
    }
    public void TestTrading_item2_6249807012730889478() throws Exception {
      SNode ti = SNodeOperations.cast(getRealNodeById("6249807012730889478"), CONCEPTS.AbstractTestItem$9u);
      TestRunner.doExecuteTest(ti);
    }

    protected TestBody(TransformationTest owner) {
      super(owner);
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept AbstractTestItem$9u = MetaAdapterFactory.getConcept(0xd441fba0f46b43cdL, 0xb723dad7b65da615L, 0x7211e50064e6dba0L, "org.iets3.core.expr.tests.structure.AbstractTestItem");
  }
}
